name: Smart contracts CI
on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          package: '@mathieu-bour/dual-contracts'
      - name: Run tests
        run: |
          cd contracts
          pnpm build
          pnpm test
